[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[remappings] = [
    v4-periphery/=lib/v4-periphery/src/
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
